### ISSUE TITLE
Possible UI improvement

### ISSUE THREAD

**Issue by lepoidev** [CMPUT301W18T23/GeoTask#29]
## I was working on modifying the TaskView xml and had a thought. What if we replaced the blank area at the bottom of the activity with the bid list?
![hmm](https://user-images.githubusercontent.com/35352972/37641113-28d222f8-2bde-11e8-9a85-e4807f181824.PNG)
## Thoughts? Its not like it is used by the keyboard. Does it fill the space well or is it too much?

**Comment by jejewittt** [comment]
I think we may have that for pictures later but idk

On Mar 20, 2018 1:32 AM, "lepoidev" <notifications@github.com> wrote:

I was working on modifying the TaskView xml and had a thought. What if we
replaced the blank area at the bottom of the activity with the bid list?

[image: hmm]
<https://user-images.githubusercontent.com/35352972/37641113-28d222f8-2bde-11e8-9a85-e4807f181824.PNG>
Thoughts? Its not like it is used by the keyboard. Does it fill the space
well or is it too much?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CMPUT301W18T23/GeoTask/issues/29>, or mute the thread
